CREATE TABLE USER_LOGIN_AUDIT
(
  LOGIN_TIME  DATE,
  USERNAME    VARCHAR2(30 BYTE),
  OSUSER      VARCHAR2(30 BYTE),
  MACHINE     VARCHAR2(30 BYTE),
  COMMAND     VARCHAR2(128 BYTE),
  PROGRAM     VARCHAR2(128 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;